name: adminlast
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  image_picker: ^1.1.2
  video_player: ^2.9.2
  uuid: ^4.5.1
  firebase_app_check: ^0.3.2
  video_compress: ^3.1.4
  permission_handler: ^11.3.1
  chewie: ^1.10.0
  file_picker: ^9.0.0
  url_launcher: ^6.1.7
  device_info_plus: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


  flutter_launcher_icons: "^0.14.3"

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logoup.jpeg"


flutter:
  uses-material-design: true

  assets:
    - assets/
